### Test de l'API
GET http://127.0.0.1:8000/

### Récupérer quelques musées
GET http://127.0.0.1:8000/museums?limit=5

### Ajouter un favori
POST http://127.0.0.1:8000/favorites
Content-Type: application/json

{
  "id": "musee-test-002",
  "name": "Musée du Louvre",
  "city": "Paris",
  "department": "75"
}

### Voir les favoris
GET http://127.0.0.1:8000/favorites

### Supprimer un favori
DELETE http://127.0.0.1:8000/favorites/musee-test-001

### vérifier après suppression
GET http://127.0.0.1:8000/favorites

### Enregistrer un utilisateur
POST http://127.0.0.1:8000/users/register
Content-Type: application/json

{
  "username": "moha",
  "email": "moha@mail.com",
  "password": "19052004"
}

### Connexion pour obtenir le token JWT
POST http://127.0.0.1:8000/users/login
Content-Type: application/json

{
  "username": "moha",
  "password": "19052004"
}

### Voir les utilisateurs enregistrés
GET http://127.0.0.1:8000/users/register


### Ajouter un favori avec le token JWT
POST http://127.0.0.1:8000/favorites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMiIsImV4cGlyZXMiOjE3NjA2OTQ2MzMuNjk1OTg4fQ.80bJs9L9n9JOitJda4X3Zwt2rtvxgQmj-McUECOSrEg

{
  "id": "M123",
  "name": "Musée du Louvre",
  "city": "Paris",
  "department": "75"
}


### Récupération des favoris du user connecté
GET http://127.0.0.1:8000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMiIsImV4cGlyZXMiOjE3NjA2OTQ2MzMuNjk1OTg4fQ.80bJs9L9n9JOitJda4X3Zwt2rtvxgQmj-McUECOSrEg
